services:
  - type: web
    name: codereview-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn data.querys.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
